apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: {{ .Values.namespace }}
  labels:
    app: client
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
      - name: dockerhub-registry
      containers:
      - name: client
        image: {{ .Values.image.registry }}/regexec:{{ .Values.image.client.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_SOCKET_URL
          value: "https://{{ .Values.ingress.host }}"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5