apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: {{ .Values.namespace }}
  labels:
    app: client
spec:
  selector:
    app: client
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP