apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: {{ .Values.namespace }}
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP